### ISSUE TITLE
DailyWeatherForecastItem is missing properties

### ISSUE THREAD

**Issue by gscpw** [thomasgalliker/OpenWeatherMap.API#13]
I am calling the Daily Forecast API:
https://openweathermap.org/forecast16

The model [`DailyWeatherForecastItem`](https://github.com/thomasgalliker/OpenWeatherMap.API/blob/develop/OpenWeatherMap/Models/DailyWeatherForecastItem.cs) does not cover all the data available.

This is what the entire payload looks like:

```json
{
  "dt": 1661857200,
  "sunrise": 1661834187,
  "sunset": 1661882248,
  "temp": {
    "day": 299.66,
    "min": 288.93,
    "max": 299.66,
    "night": 290.31,
    "eve": 297.16,
    "morn": 288.93
  },
  "feels_like": {
    "day": 299.66,
    "night": 290.3,
    "eve": 297.1,
    "morn": 288.73
  },
  "pressure": 1017,
  "humidity": 44,
  "weather": [
    {
      "id": 500,
      "main": "Rain",
      "description": "light rain",
      "icon": "10d"
    }
  ],
  "speed": 2.7,
  "deg": 209,
  "gust": 3.58,
  "clouds": 53,
  "pop": 0.7,
  "rain": 2.51
}
```

But the model covers only the following properties:

- dt
- temp
- feels_like
- clouds
- rain

Could you add the other properties, particularly `weather` prop?

**Comment by thomasgalliker** [comment]
Okay, I've extended the model and pushed a new nuget.
You'll find a new nuget package [here ](https://www.nuget.org/packages/OpenWeatherMap.API) soon. The version is 2.1.0-pre and newer. Can you let me know if it works?

**Comment by gscpw** [comment]
Thank you, it appears to be working just fine!
